### ISSUE TITLE
`prepare_dataset.py`: ModuleNotFoundError: No module named 'text'

### ISSUE THREAD

**Issue by eschmidbauer** [intory89/StyleVC#8]
Trying to prepare dataset, I get the following error:

```bash
> python prepare_dataset.py --in_dir data/VCTK/original/ --out_dir_name VCTK_16K --dataset VCTK
log directory! -----> StyleVC_VCTK
seen speakers! 87 unseen speakers! 20
start preprocessing
Traceback (most recent call last):
  File "/root/StyleVC/prepare_dataset.py", line 237, in <module>
    main()
  File "/root/StyleVC/prepare_dataset.py", line 202, in main
    from text.text_English.cleaners import english_cleaners
ModuleNotFoundError: No module named 'text'
```

Seems like something is not right with that import line.

**Comment by Superman-Valencia** [comment]
Do you solve the problem? I met the same situation.

**Comment by eschmidbauer** [comment]
i did not find a solution to this.
